import { svc } from "./lib.mts";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { detectSourceRecords, segment, DEFAULT_BUDGET } from "../../src/lib/segmentation.ts";
import { buildRunChunks } from "../../src/lib/ingestion.ts";
const { data } = await svc.from("packets").select("raw_input").eq("id", "9c564682-8959-44f9-b8ae-eb6a69bfdcae").single();
const src = String((data as any).raw_input ?? "");
writeFileSync("/tmp/icecream-source.txt", src);
console.log(`chars ${src.length}   bytes ${Buffer.byteLength(src)}   sha256 ${createHash("sha256").update(src).digest("hex").slice(0, 24)}`);
console.log(`run recorded source_len 6544  -> ${src.length === 6544 ? "MATCHES" : "DIFFERS"}`);
const det = detectSourceRecords(src);
console.log(`\nrecord detection: ${det ? `${det.records.length} records, ${det.fields} fields, delimiter ${JSON.stringify(det.delimiter)}` : "NOT a delimited table (falls back to blank-line blocks)"}`);
const blocks = src.split(/\n[ \t]*\n/).filter((b) => b.trim());
console.log(`blank-line blocks: ${blocks.length}`);
const segs = segment(src, DEFAULT_BUDGET);
console.log(`seg-v4 plan with DEFAULT_BUDGET (${JSON.stringify(DEFAULT_BUDGET)}): ${segs.length} chunks`);
console.log(`buildRunChunks: ${buildRunChunks(src).length} chunks`);
console.log(`\nfirst 3 blocks:`);
for (const b of blocks.slice(0, 3)) console.log(`   ---\n   ${b.replace(/\n/g, "\n   ").slice(0, 260)}`);
