// THE REAL IMPORT THAT EXPOSED THE PRIVACY DEFECT.
//
// A CSV whose header declares a column named `INTERNAL ONLY`, sitting beside
// one named `Client-Facing Notes`. Two records fill the internal column and one
// fills the client-facing one, which is what made the three review cards look
// identical while meaning opposite things.
//
// Synthetic throughout — example.example domains, 555 numbers — and kept as a
// TypeScript module rather than a .csv because .gitignore excludes *.csv, and
// that rule exists to keep real client data out of the repository. A fixture
// that vanishes on a clean checkout is worse than no fixture: the test that
// depends on it fails for a reason nobody can see.
export const INTERNAL_ONLY_CSV = String.raw`Firm,City,Address,Specialty,Description,Contact Name,Role,Main Phone,Direct / Secondary Phone,Email,Website,Estimate / Pricing,Timeline,Warranty,Availability,Client-Facing Notes,INTERNAL ONLY,Related / Cross-Reference
Alder & Stone Remodel,San Rafael,"1180 4th St, San Rafael, CA 94901",Full-service kitchen remodels,"Design-build contractor focused on kitchens in older Marin homes. Handles design, permitting, cabinetry coordination, electrical, plumbing, and finish work. Their proposal process usually starts with an in-home visit and a written scope.",Elena Vargas,Principal,(415) 555-0138,,elena@alderstone.example,https://alderstone.example,"Typical kitchen projects: $55,000–$90,000
 Design retainer: $2,500, credited toward construction if hired.","Design: about 2–3 weeks
 Construction: typically 8–12 weeks after permits/materials",2-year workmanship warranty,Next site visits available in about 10 days,Good fit for a client who wants one firm coordinating the whole job.,,They occasionally use Marin Cabinet Studio for specialty cabinet work.
Harbor & Pine Kitchen Co. (formerly Northstar Kitchens),Mill Valley,"36 Miller Ave, Mill Valley, CA 94941",Kitchen design + construction,"Small design-build team known for warm, traditional kitchens and detailed finish carpentry. They will work from an architect's plans or provide their own design service.",Owen Blake,Owner,(415) 555-0194,(415) 555-0187,owen@harborpine.example,https://harborpine.example,"Initial budget conversation: $70,000–$105,000 for a full kitchen.
 Cabinet allowance is quoted separately after design.",Current lead time: roughly 6 weeks to start design; construction scheduled after selections are finalized.,1-year workmanship; manufacturer warranties passed through,Booking design work for October,Client should ask whether appliance installation is included in the final construction number.,,
North Bay Buildworks,Novato,"7427 Redwood Blvd, Novato, CA 94945",General contractor / remodels,"General contractor doing kitchens, baths, additions, and structural work. Less design-forward than some of the boutique firms, but able to manage larger scopes when a kitchen project also touches walls, windows, or structural framing.",Marcus Lee,Estimator,(415) 555-0106,,marcus@northbaybuildworks.example,https://northbaybuildworks.example,"Preliminary estimate from 7/08: $52,400
 Revised estimate from 8/19: $58,900 after electrical-panel and lighting work were added.",Estimated 9–11 weeks of construction after permit issuance,1-year workmanship warranty,Could start late October if permit is ready,The two estimates reflect different scopes; both are useful context.,,
Marin Cabinet Studio,Larkspur,"280 Magnolia Ave, Larkspur, CA 94939",Custom cabinetry and millwork,"Cabinet design studio rather than a general contractor. Best used when the client already has a contractor or wants high-touch cabinet design. Offers inset, frameless, and painted custom cabinetry.",Maya Chen,Design Director,(415) 555-0161,(415) 555-0168,maya@coastlinecraft.example,https://marincabinetstudio.example,"Cabinetry for a medium kitchen often runs $28,000–$48,000 before installation.
 Design deposit: $1,500.","Design drawings: usually 2 weeks
 Cabinet production: approximately 10–14 weeks after approval",Cabinet manufacturer's warranty varies by line,Taking new design appointments,Maya's email uses the Coastline Craft domain because she works with both businesses.,,Maya Chen also manages finish selections for Coastline Craft Construction.
Baylight Design + Build,Sausalito,"215 Caledonia St, Sausalito, CA 94965",Design-build / contemporary remodels,Contemporary-focused studio with in-house design and construction management. Strong portfolio of smaller kitchens where storage and layout efficiency matter more than adding square footage.,Priya Shah,Project Consultant,(415) 555-0112,,priya@baylightdb.example,https://baylightdb.example,"Design package: $8,500
 Construction pricing comes after design development and selections.",Design phase typically 4–6 weeks,2-year workmanship warranty,Consultations available next week,Could be a good fit if the client wants help making layout decisions before pricing the build.,,
Redfern Renovation,Corte Madera,"44 Casa Buena Dr, Corte Madera, CA 94925",Construction-only remodel contractor,Construction-focused firm that often works from plans prepared by independent designers. Good for clients who already know what they want and need a contractor to execute it.,Luis Ortega,Owner,(415) 555-0143,,luis@redfernreno.example,https://redfernreno.example,"Labor + general construction estimate: $39,500
 Cabinetry, appliances, countertops, and decorative fixtures are owner-provided allowances and are not included.",About 7–9 weeks on site once materials are ready,1-year workmanship warranty,Earliest start currently mid-November,Make sure the client understands which finish materials are outside the quoted number.,"INTERNAL ONLY — Luis said he can probably hold the November slot for one week without a deposit, but does not want that promised to the client yet.",
Coastline Craft Construction,San Anselmo,"101 San Anselmo Ave, San Anselmo, CA 94960",High-end finish carpentry + remodels,"Small construction company specializing in detailed carpentry, built-ins, and kitchens. Often collaborates with independent designers and cabinet studios. Good fit for projects where finish quality matters more than the fastest schedule.",Maya Chen,Project & Design Liaison,(415) 555-0177,(415) 555-0168,maya@coastlinecraft.example,https://coastlinecraft.example,"Recent comparable kitchens: $62,000–$85,000, excluding appliances.",Typically 10–12 weeks of construction,2-year workmanship warranty,Currently estimating December starts,Same Maya Chen who appears at Marin Cabinet Studio; this is intentional and should stay on both records.,,Frequently coordinates cabinetry with Marin Cabinet Studio.
Oak & Tile Interiors,San Rafael,"1535 4th St, San Rafael, CA 94901","Design, finishes, and project coordination","Interior design studio that can handle space planning, finish selections, lighting, tile, fixtures, and contractor coordination. Does not employ construction crews directly.",Sophie Grant,Senior Designer,(415) 555-0150,,sophie@oakandtile.example,https://oakandtile.example,"Fixed design fee: $12,000 for concept through construction selections.
 Hourly consulting option: $225/hour for smaller scopes.",Design work can begin within 2 weeks,Not applicable — design services,Accepting one new kitchen project this fall,Useful if the client wants a designer but plans to bid construction separately.,,
Willow Creek Remodels,Petaluma,"620 Petaluma Blvd N, Petaluma, CA 94952",Value-oriented kitchens and baths,Family-run remodeler serving Marin and Sonoma. Offers semi-custom cabinet packages and standardized kitchen scopes intended to keep projects more predictable.,Jon Bell,Project Manager,(707) 555-0133,,jon@willowcreekremodels.example,https://willowcreekremodels.example,"Standard kitchen package starts around $42,000.
 Upgraded cabinet package starts around $49,500.
 Stone countertops are included up to a stated allowance.",Usually 6–8 weeks of construction,1-year workmanship warranty,Site visits available this month,"More standardized than the design-build firms, which may help a client who wants fewer decisions.",,
Juniper Homeworks,Fairfax,"9 Bolinas Rd, Fairfax, CA 94930",Small remodels / owner-led contractor,"Owner-led contractor doing one or two projects at a time. Juniper Homeworks often collaborates with Marin Cabinet Studio when a client wants fully custom cabinetry, but Juniper remains the construction contractor.",Rachel Kim,Owner,(415) 555-0122,,rachel@juniperhomeworks.example,https://juniperhomeworks.example,"No firm estimate yet. Site visit required before pricing.
 Rachel said projects of this size have recently ranged from about $48,000 to $75,000 depending on cabinetry and structural work.",Schedule depends on current project completion; likely 8–10 weeks after start,1-year workmanship warranty,Can schedule a site visit next Thursday,"A good candidate for a smaller, relationship-driven project.",,May use Marin Cabinet Studio for cabinets; that does not make Marin Cabinet Studio the contractor.
Delta Millwork & Build,Richmond,"1250 Marina Way S, Richmond, CA 94804",Cabinet fabrication + installation,,Andre Foster,Sales / Estimating,(510) 555-0198,,andre@deltamillwork.example,https://deltamillwork.example,"Cabinet quote: $31,750
 Installation: $6,400
 Delivery: $950",Shop drawings in 10 business days; production approximately 9 weeks,5-year cabinet-box warranty; hardware warranty by manufacturer,Production slot available if approved by September 15,This record is intentionally sparse; the source does not contain a narrative description.,,
Finch & Frame Renovation,Tiburon,"1550 Tiburon Blvd, Tiburon, CA 94920",Boutique design-build,"Boutique remodeler focused on highly customized kitchens and architectural detailing. Their process is slower and more expensive than many alternatives, but the firm handles design, finish specifications, and construction as one engagement.",Naomi Price,Client Lead,(415) 555-0181,,naomi@finchframe.example,https://finchframe.example,"Phase 1 design + feasibility: $6,000
 Phase 2 design development: $9,500
 Construction budget discussed as $95,000–$140,000, depending on cabinetry and structural scope.",Design may take 8–10 weeks before construction pricing is final,2-year workmanship warranty,New-project intake open; construction calendar is filling for winter,Probably best for a client prioritizing a highly finished result over speed or lowest cost.,INTERNAL ONLY — Naomi mentioned by phone that a current project is running late because of a specialty stone order; do not present that as a general schedule claim.,`;
