-- ============================================================================
-- ROLLBACK FOR 0054. Not a migration; kept outside supabase/migrations.
--
-- Drops the backfill token and the backfill function. It touches no row:
-- publications already backfilled stay exactly as they are, because once readers
-- use them, deleting one takes a Sendset's page offline. Removing backfilled rows
-- is a separate, deliberate step: the manifest-bound SQL generated by
-- `scripts/publication-backfill.mts rollback-sql <manifest>`, which deletes a row
-- only while its content digest and published_at still match the manifest.
-- ============================================================================

begin;

drop function public.backfill_packet_publication(uuid, jsonb, smallint, jsonb);
drop function public.packet_backfill_token(uuid);

do $$
begin
  if to_regprocedure('public.backfill_packet_publication(uuid,jsonb,smallint,jsonb)') is not null
     or to_regprocedure('public.packet_backfill_token(uuid)') is not null then
    raise exception 'ROLLBACK 0054 INCOMPLETE: an 0054 object survived.';
  end if;
end $$;

commit;
